import { builtinModules } from "node:module";
import { copyFile, rm } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";

const projectRoot = fileURLToPath(new URL(".", import.meta.url));
const outDir = resolve(projectRoot, "dist");
const bundledFileName = "main.js";
const bundledStyleFileName = "styles.css";
const externalPackages = new Set([
	"obsidian",
	"electron",
	...builtinModules,
	...builtinModules.map((moduleName) => `node:${moduleName}`),
]);
const externalPrefixes = ["@codemirror/", "@lezer/"];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

function isExternal(id: string): boolean {
	return externalPackages.has(id) || externalPrefixes.some((prefix) => id.startsWith(prefix));
}

function copyBundleToPluginRoot() {
	return {
		name: "copy-bundle-to-plugin-root",
		closeBundle: async () => {
			await Promise.all([
				copyFile(resolve(outDir, bundledFileName), resolve(projectRoot, bundledFileName)),
				copyFile(
					resolve(outDir, bundledStyleFileName),
					resolve(projectRoot, bundledStyleFileName),
				),
			]);
			await rm(outDir, { force: true, recursive: true });
		},
	};
}

/**
 * Obsidian loads `main.js` as CommonJS. Rolldown keeps lazily imported Node
 * built-ins (used by the dictionary's desktop-only importer) as `import(...)`
 * expressions, so rewrite them to `require(...)` inside a resolved promise.
 */
function bundleDeferredNodeImports() {
	return {
		name: "bundle-deferred-node-imports",
		enforce: "post" as const,
		renderChunk(code: string) {
			const bundled = code.replace(
				/\bimport\((["'`])(node:[^"'`]+)\1\)/g,
				(_match, quote: string, moduleId: string) =>
					`Promise.resolve().then(() => require(${quote}${moduleId}${quote}))`,
			);
			return bundled === code ? null : { code: bundled, map: null };
		},
	};
}

export default defineConfig(({ mode }) => {
	const isProduction = mode === "production";

	return {
		css: {
			modules: {
				localsConvention: "camelCase",
				generateScopedName: "fc-[name]__[local]_[hash:base64:5]",
			},
		},
		build: {
			// The dictionary engine WASM (654 KiB) must stay inside main.js: the
			// copy step below deletes dist/, so any emitted asset would be lost.
			assetsInlineLimit: 1_048_576,
			copyPublicDir: false,
			lib: {
				entry: resolve(projectRoot, "src/core/host/main.ts"),
				formats: ["cjs"],
				cssFileName: "styles",
				fileName: () => bundledFileName,
			},
			cssCodeSplit: false,
			cssMinify: false,
			minify: isProduction,
			outDir,
			rolldownOptions: {
				external: isExternal,
				onLog(level, log, defaultHandler) {
					if (log.code === "MODULE_LEVEL_DIRECTIVE") {
						return;
					}
					defaultHandler(level, log);
				},
				output: {
					banner,
					codeSplitting: false,
					entryFileNames: bundledFileName,
					exports: "named",
				},
			},
			sourcemap: isProduction ? false : "inline",
			target: "es2018",
		},
		define: {
			"process.env.NODE_ENV": JSON.stringify(isProduction ? "production" : "development"),
		},
		esbuild: {
			jsx: "automatic",
		},
		plugins: [bundleDeferredNodeImports(), copyBundleToPluginRoot()],
	};
});
