import type { Language } from "../../../core/shared/types";

const zh = {
	title: "本地视频",
	openFailed: "无法打开本地视频播放器，请重试。",
	disabled: "本地视频播放器尚未启用，请前往设置开启。",
	openSettings: "打开播放器设置",
	addVideos: "添加视频",
	emptyTitle: "添加本地视频开始学习",
	emptyDescription: "视频保留在电脑原位置，路径和观看进度只保存在本机。",
	play: "播放",
	pause: "暂停",
	previous: "上一个",
	next: "下一个",
	backward: "后退 10 秒",
	forward: "前进 10 秒",
	floating: "悬浮播放",
	dockAndPause: "返回分屏并暂停",
	remove: "移除",
	replace: "重新选择",
	moveUp: "上移",
	moveDown: "下移",
	queue: "播放队列",
	rate: "播放速度",
	missing: "找不到或无法读取该视频。它可能已被移动，或所在磁盘尚未连接。",
	decodeError: "无法读取或播放该视频。请检查文件路径，并确认系统支持它的编码格式。",
	selectFailed: "无法读取所选视频，请重试。",
	activeElsewhere: "播放器已在另一个视图中打开。",
	focusPlayer: "打开现有播放器",
	completed: "已看完",
	settingsHeading: "本地视频",
	settingsGeneral: "常规设置",
	enabled: "启用本地视频播放器",
	enabledDescription: "在工作台和命令面板中提供桌面本地视频播放器。",
	localData: "本机播放器数据",
	localDataDescription: "清除本机保存的视频列表、观看位置、倍速和浮窗位置。",
	clearLocalData: "清除本机数据",
	cleared: "已清除本机视频播放器数据。",
};

const en: typeof zh = {
	title: "Local video",
	openFailed: "Unable to open the local video player. Please try again.",
	disabled: "The local video player is disabled. Enable it in Settings.",
	openSettings: "Open player settings",
	addVideos: "Add videos",
	emptyTitle: "Add a local video to start studying",
	emptyDescription:
		"Videos stay in their original location. Paths and viewing positions remain on this device.",
	play: "Play",
	pause: "Pause",
	previous: "Previous",
	next: "Next",
	backward: "Back 10 seconds",
	forward: "Forward 10 seconds",
	floating: "Float player",
	dockAndPause: "Dock and pause",
	remove: "Remove",
	replace: "Choose replacement",
	moveUp: "Move up",
	moveDown: "Move down",
	queue: "Playback queue",
	rate: "Playback speed",
	missing: "This video cannot be found or read. It may have moved or its disk is offline.",
	decodeError:
		"This video cannot be read or played. Check its path and that your system supports its codec.",
	selectFailed: "The selected video could not be read. Please try again.",
	activeElsewhere: "The player is already open in another view.",
	focusPlayer: "Open existing player",
	completed: "Completed",
	settingsHeading: "Local video",
	settingsGeneral: "General",
	enabled: "Enable local video player",
	enabledDescription: "Adds the desktop local video player to the workbench and command palette.",
	localData: "Device-local player data",
	localDataDescription:
		"Clear the saved queue, viewing positions, playback rate, and floating position on this device.",
	clearLocalData: "Clear local data",
	cleared: "Local video player data cleared.",
};

export function videoPlayerStrings(language: Language): typeof zh {
	return language === "en" ? en : zh;
}
