import type { Language } from "../../../core/shared/types";

const zh = {
	title: "本地视频",
	openFailed: "无法打开本地视频播放器，请重试。",
	disabled: "本地视频播放器尚未启用，请前往设置开启。",
	openSettings: "打开播放器设置",
	addVideos: "添加视频",
	emptyTitle: "添加本地视频开始学习",
	emptyDescription: "视频保留在电脑原位置，路径和观看进度只保存在本机。",
	play: "播放",
	pause: "暂停",
	previous: "上一个",
	next: "下一个",
	backward: (seconds: number) => `后退 ${seconds} 秒`,
	forward: (seconds: number) => `前进 ${seconds} 秒`,
	floating: "悬浮播放",
	dockAndPause: "返回分屏并暂停",
	remove: "移除",
	replace: "重新选择",
	moveUp: "上移",
	moveDown: "下移",
	queue: "播放队列",
	queueSummary: (count: number, current: number) =>
		`播放队列 · ${count} 个${current > 0 ? ` · 正在播放 ${current}/${count}` : ""}`,
	queueExpand: "展开播放队列",
	queueCollapse: "折叠播放队列",
	queueActions: "视频操作",
	dragToReorder: "拖动排序",
	watched: (time: string) => `已观看 ${time}`,
	rate: "播放速度",
	progress: "播放进度",
	playerRegion: "视频播放器",
	settings: "播放器设置",
	resizeLeft: "从左下角调整浮窗大小",
	resizeRight: "从右下角调整浮窗大小",
	missing: "找不到或无法读取该视频。它可能已被移动，或所在磁盘尚未连接。",
	decodeError: "无法读取或播放该视频。请检查文件路径，并确认系统支持它的编码格式。",
	selectFailed: "无法读取所选视频，请重试。",
	activeElsewhere: "播放器已在另一个视图中打开。",
	focusPlayer: "打开现有播放器",
	completed: "已看完",
	settingsHeading: "本地视频",
	settingsGeneral: "常规设置",
	skipInterval: "快进与快退秒数",
	skipIntervalDescription: "控制播放器按钮和快捷键每次跳转的时长。",
	seconds: (seconds: number) => `${seconds} 秒`,
	keyboardSettings: "播放快捷键",
	shortcutNames: {
		togglePlayback: "播放 / 暂停",
		seekBackward: "快退",
		seekForward: "快进",
	},
	shortcutDescription: "点击按键框，然后按下一个按键或组合键。仅在播放器获得焦点时生效。",
	shortcutUnassigned: "未分配",
	shortcutRecording: "请按快捷键…",
	shortcutConflict: "此快捷键已用于另一个播放操作。",
	shortcutClear: "清除",
	shortcutReset: "恢复默认",
	enabled: "启用本地视频播放器",
	enabledDescription: "在工作台和命令面板中提供桌面本地视频播放器。",
	localData: "本机播放器数据",
	localDataDescription: "清除本机保存的播放队列、观看位置、倍速、折叠状态和浮窗位置。",
	clearLocalData: "清除本机数据",
	cleared: "已清除本机视频播放器数据。",
};

const en: typeof zh = {
	title: "Local video",
	openFailed: "Unable to open the local video player. Please try again.",
	disabled: "The local video player is disabled. Enable it in Settings.",
	openSettings: "Open player settings",
	addVideos: "Add videos",
	emptyTitle: "Add a local video to start studying",
	emptyDescription:
		"Videos stay in their original location. Paths and viewing positions remain on this device.",
	play: "Play",
	pause: "Pause",
	previous: "Previous",
	next: "Next",
	backward: (seconds: number) => `Back ${seconds} seconds`,
	forward: (seconds: number) => `Forward ${seconds} seconds`,
	floating: "Float player",
	dockAndPause: "Dock and pause",
	remove: "Remove",
	replace: "Choose replacement",
	moveUp: "Move up",
	moveDown: "Move down",
	queue: "Playback queue",
	queueSummary: (count: number, current: number) =>
		`Playback queue · ${count}${current > 0 ? ` · Playing ${current}/${count}` : ""}`,
	queueExpand: "Expand playback queue",
	queueCollapse: "Collapse playback queue",
	queueActions: "Video actions",
	dragToReorder: "Drag to reorder",
	watched: (time: string) => `Watched ${time}`,
	rate: "Playback speed",
	progress: "Playback progress",
	playerRegion: "Video player",
	settings: "Player settings",
	resizeLeft: "Resize floating player from bottom left",
	resizeRight: "Resize floating player from bottom right",
	missing: "This video cannot be found or read. It may have moved or its disk is offline.",
	decodeError:
		"This video cannot be read or played. Check its path and that your system supports its codec.",
	selectFailed: "The selected video could not be read. Please try again.",
	activeElsewhere: "The player is already open in another view.",
	focusPlayer: "Open existing player",
	completed: "Completed",
	settingsHeading: "Local video",
	settingsGeneral: "General",
	skipInterval: "Skip interval",
	skipIntervalDescription: "Controls how far the player buttons and shortcuts seek.",
	seconds: (seconds: number) => `${seconds} seconds`,
	keyboardSettings: "Playback shortcuts",
	shortcutNames: {
		togglePlayback: "Play / pause",
		seekBackward: "Seek backward",
		seekForward: "Seek forward",
	},
	shortcutDescription:
		"Select the key field, then press one key or key combination. It only works while the player has focus.",
	shortcutUnassigned: "Unassigned",
	shortcutRecording: "Press shortcut…",
	shortcutConflict: "This shortcut is already used by another playback action.",
	shortcutClear: "Clear",
	shortcutReset: "Reset",
	enabled: "Enable local video player",
	enabledDescription: "Adds the desktop local video player to the workbench and command palette.",
	localData: "Device-local player data",
	localDataDescription:
		"Clear the saved queue, viewing positions, playback rate, disclosure state, and floating position on this device.",
	clearLocalData: "Clear local data",
	cleared: "Local video player data cleared.",
};

export function videoPlayerStrings(language: Language): typeof zh {
	return language === "en" ? en : zh;
}
